-- =====================================================================================
-- CampusDesk - PostgreSQL schema (all names in English)
--
-- Usage (optional: the application can also create the tables by itself with DDL_AUTO=update):
--   1. createdb campusdesk            (or CREATE DATABASE campusdesk; from pgAdmin)
--   2. psql -d campusdesk -f database/schema.sql
--   3. Start the backend with DDL_AUTO=validate
-- The first administrator is NOT created here: the backend creates it on startup from the
-- ADMIN_EMAIL / ADMIN_PASSWORD environment variables, so no password lives in this repository.
-- =====================================================================================

CREATE TABLE IF NOT EXISTS roles (
    name         VARCHAR(50)  PRIMARY KEY,
    description  VARCHAR(255) NOT NULL,
    system_role  BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_name   VARCHAR(50) NOT NULL,
    permission  VARCHAR(50) NOT NULL,
    PRIMARY KEY (role_name, permission),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_name) REFERENCES roles (name) ON DELETE CASCADE,
    CONSTRAINT ck_role_permissions_permission CHECK (permission IN (
        'TICKET_CREATE', 'TICKET_READ_OWN', 'TICKET_READ_ASSIGNED', 'TICKET_READ_ALL',
        'TICKET_EDIT_OWN', 'TICKET_CLOSE_OWN', 'TICKET_ASSIGN', 'TICKET_WORK',
        'COMMENT_CREATE', 'USERS_READ', 'USERS_MANAGE', 'ROLES_MANAGE'))
);

CREATE TABLE IF NOT EXISTS users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(120) NOT NULL,
    email          VARCHAR(150) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,           -- BCrypt hash, never plain text
    role_name      VARCHAR(50)  NOT NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_name) REFERENCES roles (name)
);

CREATE TABLE IF NOT EXISTS tickets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(150)  NOT NULL,
    description    VARCHAR(4000) NOT NULL,
    category       VARCHAR(20)   NOT NULL,
    priority       VARCHAR(20)   NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    requester_id   BIGINT        NOT NULL,
    technician_id  BIGINT,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_tickets_requester  FOREIGN KEY (requester_id)  REFERENCES users (id),
    CONSTRAINT fk_tickets_technician FOREIGN KEY (technician_id) REFERENCES users (id),
    CONSTRAINT ck_tickets_category CHECK (category IN ('HARDWARE', 'SOFTWARE', 'NETWORK', 'ACCESS', 'OTHER')),
    CONSTRAINT ck_tickets_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_tickets_status   CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);
CREATE INDEX IF NOT EXISTS idx_tickets_status     ON tickets (status);
CREATE INDEX IF NOT EXISTS idx_tickets_requester  ON tickets (requester_id);
CREATE INDEX IF NOT EXISTS idx_tickets_technician ON tickets (technician_id);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(2000) NOT NULL,
    ticket_id   BIGINT        NOT NULL,
    author_id   BIGINT        NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);
CREATE INDEX IF NOT EXISTS idx_comments_ticket ON comments (ticket_id);

-- Append-only audit trail of status changes (previous_status is NULL only for the creation entry).
CREATE TABLE IF NOT EXISTS status_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id        BIGINT      NOT NULL,
    previous_status  VARCHAR(20),
    new_status       VARCHAR(20) NOT NULL,
    changed_by_id    BIGINT      NOT NULL,
    changed_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    note             VARCHAR(255),
    CONSTRAINT fk_history_ticket FOREIGN KEY (ticket_id)     REFERENCES tickets (id),
    CONSTRAINT fk_history_user   FOREIGN KEY (changed_by_id) REFERENCES users (id),
    CONSTRAINT ck_history_previous CHECK (previous_status IS NULL
        OR previous_status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT ck_history_new CHECK (new_status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);
CREATE INDEX IF NOT EXISTS idx_status_history_ticket ON status_history (ticket_id);

-- ------------------------------------------------------------------------------------
-- System roles and their permissions (the backend also keeps these in sync on startup)
-- ------------------------------------------------------------------------------------
INSERT INTO roles (name, description, system_role) VALUES
    ('ADMIN',      'Full access to tickets, users, roles and statistics', TRUE),
    ('TECHNICIAN', 'Works on the tickets assigned to them', TRUE),
    ('USER',       'Creates and follows their own support requests', TRUE)
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_name, permission) VALUES
    ('ADMIN', 'TICKET_CREATE'), ('ADMIN', 'TICKET_READ_OWN'), ('ADMIN', 'TICKET_READ_ASSIGNED'),
    ('ADMIN', 'TICKET_READ_ALL'), ('ADMIN', 'TICKET_EDIT_OWN'), ('ADMIN', 'TICKET_CLOSE_OWN'),
    ('ADMIN', 'TICKET_ASSIGN'), ('ADMIN', 'TICKET_WORK'), ('ADMIN', 'COMMENT_CREATE'),
    ('ADMIN', 'USERS_READ'), ('ADMIN', 'USERS_MANAGE'), ('ADMIN', 'ROLES_MANAGE'),
    ('TECHNICIAN', 'TICKET_READ_ASSIGNED'), ('TECHNICIAN', 'TICKET_WORK'), ('TECHNICIAN', 'COMMENT_CREATE'),
    ('USER', 'TICKET_CREATE'), ('USER', 'TICKET_READ_OWN'), ('USER', 'TICKET_EDIT_OWN'),
    ('USER', 'TICKET_CLOSE_OWN'), ('USER', 'COMMENT_CREATE')
ON CONFLICT DO NOTHING;
